### ISSUE TITLE
use finagle Name instead of static host:port

### ISSUE THREAD

**Issue by dantheman46** [openzipkin/zipkin-finagle#7]
Maybe it will be better to use finagle com.twitter.finagle.Name instead of static host:port.

In case of Name we could get those host port from Service Discovery and change it dynamically...

**Comment by adriancole** [comment]
I suppose you are referring to http? kafka has its own service discovery thing.

If you're referring to http, there's a problem of determining the value of the host header..

**Comment by adriancole** [comment]
(ps all ears if you have a proposal for how this might work concretely, for example a code snipped of a finagle http client that uses c.t.f.Name and also sets host header)

**Comment by dantheman46** [comment]
No I'm not referring to http at all.
c.t.f.Name is from finagle-core module and have nothing in common with HTTP.

Name contanins **updateable(Var)** set of com.twitter.finagle.Address constructed from InetSocketAddress
 def apply(addr: InetSocketAddress): Address

The key word is updateable/observable. Name give us this feature 

When writing this post I have realized that we do not need this because kafka has some features that takes care of HA - like hearbeat, notifications etc and driver is able to connect to another working broker.

I need some time to verify this feature besause sometimes it works sometimes not...
I do not know why at the moment

Regards
Daniel

**Comment by adriancole** [comment]
So right now, we can easily use Name from finagle libraries like http and thrift. That's because they are built to use them. It seems a nice idea to have all things use the same lookup mechanism, but in reality not everything was written to use Finagle's resolver.

Kafka has its own dynamic address management, starting with a given list of bootstrap addresses. We could use Name.Bound to populate that initial list, but future updates would be up to Kafka.

If this is helpful, despite the limitations, ping back. I'd like at least one more nod before digging into this. cc @klingerf
