### ISSUE TITLE
Update build to support multiple scala version

### ISSUE THREAD

**Issue by crispywalrus** [openzipkin/zipkin-finagle#75]
So far matching scala versions has been only mildly annoying. Mostly because I've been happy with 2.12 (and the only option has been backing up to 2.11) Now finagle builds with 2.13. It's not yet part of the publishing process so any experimentation needs to be done with locally built version. That said supporting 2.12 and 2.11 has proved difficult with maven as the build tool. Adding 2.13 which is going to be desired soon just increases the problems. There needs to be some concordance about how to build against multiple versions of scala.

**Comment by adriancole** [comment]
here's a last comment on this from @abesto  https://github.com/openzipkin/zipkin-finagle/issues/21#issuecomment-285039208

My thinking is that this could be "easy enough" as long as there are no compilation failures between the two scala versions. For example, you choose a master version (ex 2.12) then the deploy part of the script runs again after a find/replace 2.12/2.13 (have to find/replace because the group ID cannot be parameterized iiuc).

ex. after normal publish
```bash
# do some findy replacey stuff which dirties the checkout, but it doesn't matter as the slave is throwaway
# run the deploy and central sync part again
--snip--
./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DskipTests deploy
--snip--
```

**Comment by adriancole** [comment]
I'm going to try this manually for now and paste back instructions.

**Comment by adriancole** [comment]
Here's how I started then I realized we couldn't use bintray two packages for same group ID

```bash
# checkout the thing already released
$ git checkout 2.2.0
# switch all the versions to scala 2.13 based on naming convention
$ find . -type f -name pom.xml | xargs sed -i '' 's/_2.12/_2.13/g'
# change bintray to zipkin-finagle_2.13 in the plugin and also repositories.. sorry didn't script this yet.
$ vi pom.xml
# deploy jars to bintray with my credentials (like what travis would do)
$ BINTRAY_USER=adriancole BINTRAY_KEY=XXXXXX ./mvnw --batch-mode -s ./.settings.xml -Prelease -nsu -DskipTests deploy
```
The above didn't fail, just I couldn't link it to jcenter for maven central sync. I will delete the zipkin-finagle_2.13 package since we can't use it.

eg delete this: https://bintray.com/openzipkin/maven/zipkin-finagle_2.13

**Comment by adriancole** [comment]
wow it seems now that bintray will let you upload twice to the same version.. I think we can solve this one!

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-finagle/pull/89
